name: Deploy

on:
  workflow_run:
    # Publish `master` as Docker `latest` image.
    workflows: ["DockerBuild"]
    branches: [main]
    types: 
      - completed


env:
  IMAGE_NAME: clarkchenme/flask-hello:v1
  CONTAINER_NAME: flask-hello-service

jobs:
  build:
    name: Build
    environment: Product
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo  ${{ secrets.HOST }}

    - name: test IMAGE_NAME
      run: echo $IMAGE_NAME

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host:  ${{ secrets.HOST }}
        username:  ${{ secrets.SSH_USER }}
        password:  ${{ secrets.SSH_USER_PWD }}
        port: 22
        envs: IMAGE_NAME,CONTAINER_NAME
        script: |
          echo $IMAGE_NAME
          docker container stop $CONTAINER_NAME
          docker container rm $CONTAINER_NAME
          docker pull $IMAGE_NAME
          docker rmi -f $(docker images|awk '/none/{print $3}')
          docker run -p 5000:5000 -d  --name $CONTAINER_NAME $IMAGE_NAME

